<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>0.2.0</Version>
        <Authors>jmhickman</Authors>
        <Description>Library for Active Directory enumeration</Description>
        <Copyright>2026</Copyright>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/jmhickman/Fiewport</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <LangVersion>9.0</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
        <Content Include="LICENSE" />
        <Compile Include="src\AssemblyInfo.fs"/>
        <Compile Include="src\Types.fs" />
        <Compile Include="src\FileOperations.fs" />
        <Compile Include="src\FauliAuth.fs" />
        <Compile Include="src\LdapWire.fs" />
        <Compile Include="src\LdapSearch.fs" />
        <Compile Include="src\LDAPConstants.fs" />
        <Compile Include="src\SecurityDescriptor.fs" />
        <Compile Include="src\LDAPDataHandlers.fs" />
        <Compile Include="src\LDAPUtils.fs" />
        <Compile Include="src\Mold.fs" />
        <Compile Include="src\Filter.fs" />
        <Compile Include="src\Tee.fs" />
        <Compile Include="src\PrettyPrinter.fs" />
        <Compile Include="src\Searcher.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="../Fauli/Fauli.fsproj"/>
      <PackageReference Include="EluciusFTW.SpectreCoff" Version="0.54.7" />
      <PackageReference Include="Fauli" Version="2026.8.13" />
      <PackageReference Include="MessagePack" Version="3.1.8" />
      <PackageReference Include="MessagePack.FSharpExtensions" Version="4.0.0" />

      <PackageReference Update="FSharp.Core" Version="9.0.201" />
    </ItemGroup>

</Project>
